register(
    GRAMPLET,
    id="LocalTerm Gramplet",
    name=_("Dictionary"),
    description=_("Localized index to Gramps Glossary terms"),
    authors=["Kaj Mikkelsen"],
    status=EXPERIMENTAL,
    version = '0.1.1',
    fname="LocalTerm.py",
    height=20,
    detached_width=510,
    detached_height=480,
    expand=True,
    gramplet="LocalTerm",
    gramplet_title=_("Dictionary for Gramps"),
    gramps_target_version="5.2",
    help_url="https://github.com/kajmikkelsen/LocalTerm",
#    help_url="Addon:Historical_Context",
    navtypes=["Person", "Dashboard", "Note"],
    include_in_listing=True,
)
