register(
    GRAMPLET,
    id="LocalTerm Gramplet",
    name=_("Dictionary"),
    description=_("Dictionary for gramps objects"),
    status=STABLE,
    version = '0.1.1',
    fname="LocalTerm.py",
    height=20,
    detached_width=510,
    detached_height=480,
    expand=True,
    gramplet="LocalTerm",
    gramplet_title=_("Dictionary for gramps"),
    gramps_target_version="5.2",
#    help_url="Addon:Historical_Context",
    navtypes=["Person", "Dashboard"],
    include_in_listing=True,
)
